The correct method to join two NumPy arrays along a particular axis is:

1. np.concatenate

Joins two or more arrays along an existing axis specified by the axis parameter (e.g., axis=0 for vertical stacking, axis=1 for horizontal stacking in 2D arrays).

Most general function, can concatenate along any axis of arrays with compatible shapes.

In [1]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Concatenate along rows (vertical)
print(np.concatenate((a, b), axis=0))

# Concatenate along columns (horizontal)
print(np.concatenate((a, b), axis=1))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


2. np.append

Appends values to the end of an array along a specified axis (default appends flattened array).

Less efficient for large arrays as it creates a new copy.

Usually used for adding elements rather than full array concatenation.

3. np.hstack

Horizontally stacks arrays, equivalent to np.concatenate with axis=1 for 2D arrays.

Stacks arrays column-wise, requires matching number of rows.

4. np.vstack

Vertically stacks arrays, equivalent to np.concatenate with axis=0 for 2D arrays.

Stacks arrays row-wise, requires matching number of columns.

Summary:

np.concatenate joins arrays along any specified axis.

np.append flattens arrays by default but can append along an axis if specified.

np.hstack stacks arrays horizontally (axis=1).

np.vstack stacks arrays vertically (axis=0).

Use np.concatenate for flexible joining along any axis

In [2]:
import numpy as np

# Define two 2x2 arrays
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])

# 1. Using np.concatenate (general method)
# Concatenate vertically (axis=0)
concat_axis0 = np.concatenate((a, b), axis=0)
print("Concatenate along axis 0 (vertical):\n", concat_axis0)

# Concatenate horizontally (axis=1)
concat_axis1 = np.concatenate((a, b), axis=1)
print("\nConcatenate along axis 1 (horizontal):\n", concat_axis1)

# 2. Using np.append (flattened by default, so reshaping required)
append_flat = np.append(a, b)
print("\nAppend (flattened):\n", append_flat)

# Append along axis 0 requires reshaping to 2D
append_axis0 = np.append(a, b, axis=0)
print("\nAppend along axis 0:\n", append_axis0)

# 3. Using np.hstack (horizontal stacking)
hstacked = np.hstack((a, b))
print("\nHorizontal stack (hstack):\n", hstacked)

# 4. Using np.vstack (vertical stacking)
vstacked = np.vstack((a, b))
print("\nVertical stack (vstack):\n", vstacked)


Concatenate along axis 0 (vertical):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenate along axis 1 (horizontal):
 [[1 2 5 6]
 [3 4 7 8]]

Append (flattened):
 [1 2 3 4 5 6 7 8]

Append along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stack (hstack):
 [[1 2 5 6]
 [3 4 7 8]]

Vertical stack (vstack):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


#heading 

## rejeiusbbdew

### Hiwindiwedn

<h1>Times ahead </h1>

***Boldihwbduwybd***

---

<hr/>