Dimensions in the array: means the level of depth
0-D : Scalar(single number)
1-D : Vector(list of number)
2-D : Matrix(table/grid)
3-D : Tensor(stack of matrices)
4-D+ : Higher order tensors

0-D Array(Scalar)

In [ ]:
import numpy as np

#Directly specify the single value
arr = np.array(10)
print(arr)

#find dimension
print(arr.ndim) #This is just a single number so it has 0 dimension
print(arr.shape)

10
0
()


1-D Array(One-Dimensional Array) (VECTOR)

In [2]:
#Creating 1D arrays
vector_1 = np.array([1,2,3,4,5])
print("1D array examples: ")
print(f"vector_1 : , {vector_1}")
print(f" Dimensions: {vector_1.ndim}")
print(f" Shape: {vector_1.shape}")
print(f" Size: {vector_1.size}")
print(f" Length(len): {len(vector_1)}")

1D array examples: 
vector_1 : , [1 2 3 4 5]
 Dimensions: 1
 Shape: (5,)
 Size: 5
 Length(len): 5


2-D Array(Two-Dimensional Arrays) (MATRICES) 

In [7]:
import numpy as np

#Creating 2d arrays
matrix_1 = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])

print("2D array examples : ")
print(f"matrix_1:\n{matrix_1}")
print(f"Dimensions : {matrix_1.ndim}")
print(f"Shape: {matrix_1.shape} ->(rows, columns)")
print(f"Size : {matrix_1.size}")
print(f"Length (len) : {len(matrix_1)} ->(number of rows)")

2D array examples : 
matrix_1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensions : 2
Shape: (3, 3) ->(rows, columns)
Size : 9
Length (len) : 3 ->(number of rows)


3-D Arrays (3 Dimensional arrays)

In [8]:
import numpy as np

#creation 3D arrays
#method 1: Direct creation
array_3d = np.array([[[1,2,3],[4,5,6]],
                     [[7,8,9],[10,11,12]],
                     [[13,14,15],[16,17,18]]])

print("3D Array Examples : ")
print(f"array_3d shape: {array_3d.shape}")
print(f"Dimensions : {array_3d.ndim}")
print(f"Size : {array_3d.size}")

3D Array Examples : 
array_3d shape: (3, 2, 3)
Dimensions : 3
Size : 18


Higher Dimensions (n-D Arrays): Arrays with more than 3 dimensions.

In [9]:
import numpy as np
arr = np.array([1,2,3,4], ndmin = 5)
print(arr)
print("Dimension: ", arr.ndim)
print("Shape : ", arr.shape)


[[[[[1 2 3 4]]]]]
Dimension:  5
Shape :  (1, 1, 1, 1, 4)


NumPy asarray()

In [ ]:
import numpy as np
list_data = [1,2,3,4,5]
arr_from_list = np.asarray(list_data)
print("From list: ", arr_from_list) 
print("Shape:", arr_from_list.shape)
print("Data type:", arr_from_list.dtype)

#From Python tuple
tuple_data = (6,7,8,9,10)
arr_from_tuple = np.asarray(tuple_data)
print("\nFrom tuple:", arr_from_tuple)

From list:  [1 2 4 5]
Shape: (4,)
Data type: int64

From tuple: [ 6  7  8  9 10]


In [14]:
# array and asarray
original = [1, 2, 3, 4, 5]
num_arr = np.array(original)      
num_arr[0] = 99
print(num_arr)
print(original)


[99  2  3  4  5]
[1, 2, 3, 4, 5]


In [13]:
original = [1, 2, 3, 4, 5]
numpy_arr = np.array(original) 
as_num_arr = np.asarray(numpy_arr)
as_num_arr[0] = 88
print(as_num_arr)
print(numpy_arr)

[88  2  3  4  5]
[88  2  3  4  5]


Numpy eye() Function

1. Basic Example

In [10]:
import numpy as np
arr = np.eye(3)
print(arr)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


2. Creating a Non-Square Matrix

In [ ]:
import numpy as np
arr = np.eye(3,5)   #3 rows and 5 columns
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


NumPy eye() Function: Using k parameter we can shift the diagonal up or down.

In [13]:
import numpy as np 
print(np.eye(4, k=1))
#Diagonal above the main


[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [15]:
import numpy as np 
print(np.eye(4, k=-1))
#Diagonal below the main


[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


k = 1 -> Moves the diagonal up by one row. and
k = -1 -> Moves the diagonal down by one row

NumPy identity() Function

In [16]:
import numpy as np

#2x2 identity matrix
identity_2x2 = np.identity(2)

#only one parameter (n) -> always
#creates a square matrix.
print("2x2 Identity Matrix :")
print(identity_2x2)
print(f"Shape:  {identity_2x2.shape}")
print(f"Data type: {identity_2x2.dtype}\n")

2x2 Identity Matrix :
[[1. 0.]
 [0. 1.]]
Shape:  (2, 2)
Data type: float64



In [17]:
import numpy as np
#3x3 identity matrix
identity_3x3 = np.identity(3)
print("3x3 identity Matrix : ")
print(identity_3x3)
print(f"Sahpe: {identity_3x3.shape}\n")


3x3 identity Matrix : 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Sahpe: (3, 3)



numpy.zeros_like()

In [18]:
import numpy as np

#create a template array
template = np.array([[1,2,3],[4,5,6]])
print("Template array : ")
print(template)
print(f"Shape: {template.shape}, dtype: {template.dtype}\n")

Template array : 
[[1 2 3]
 [4 5 6]]
Shape: (2, 3), dtype: int64



In [20]:
import numpy as np
#create zeros array with same shape and dtype
zeros_array = np.zeros_like(template)
print(zeros_array)
print(f"Shape : {zeros_array.shape}, dtype: {zeros_array.dtype}\n")

[[0 0 0]
 [0 0 0]]
Shape : (2, 3), dtype: int64



numpy.ones_like()

In [22]:
import numpy as np
#create a template array
template = np.array([[1,2,3],[4,5,6]])
print("Template array")
print(template)
print(f"Shape : {template.shape}, dtype: {template.dtype}\n")

Template array
[[1 2 3]
 [4 5 6]]
Shape : (2, 3), dtype: int64



In [23]:
#create ones array with same shape and dtype
ones_array = np.ones_like(template)
print("ones_like result : ")
print(ones_array)
print(f"Shape : {ones_array.shape}, dtype: {ones_array.dtype}\n")

ones_like result : 
[[1 1 1]
 [1 1 1]]
Shape : (2, 3), dtype: int64



Numpy.ones_like()-using the shape parameter

In [25]:
import numpy as np
#create a template array
template = np.array([[1,2,3],[4,5,6]])
print("Template array : ")
print(template)
print(f"Shape : {template.shape}, dtype: {template.dtype}\n")

#create ones array with overridden shape
ones_array = np.ones_like(template, shape = (3,2))
print("ones_like result with shape = (3,2): ")
print(ones_array)
print(f"Shape : {ones_array.shape}, dtype: {ones_array.dtype}\n")

Template array : 
[[1 2 3]
 [4 5 6]]
Shape : (2, 3), dtype: int64

ones_like result with shape = (3,2): 
[[1 1]
 [1 1]
 [1 1]]
Shape : (3, 2), dtype: int64



Numpy.empty_like()

In [29]:
import numpy as np
template = ([[1,2,3], 
             [4,5,6]])

empty_arr = np.empty_like(template)
print("Template array : ")
print(template)


print("\nEmpty-like result: ")
print(empty_arr)
print(f"Shape : {empty_arr.shape},dtype : {empty_arr.dtype}")



Template array : 
[[1, 2, 3], [4, 5, 6]]

Empty-like result: 
[[3559076683359191040                1864                   0]
 [      2324567260640                   0        279172940033]]
Shape : (2, 3),dtype : int64


In [28]:
print("\nEmpty-like result: ")
print(empty_arr)
print(f"Shape : {empty_arr.shape},dtype : {empty_arr.dtype}")


Empty-like result: 
[[1 1 1]
 [1 1 1]]
Shape : (2, 3),dtype : int64


Numpy.full_like()

In [30]:
import numpy as np
template = np.array([[1,2,3],[4,5,6]])
print("Template array: ")
print(template)

Template array: 
[[1 2 3]
 [4 5 6]]


In [31]:
filled_array = np.full_like(template, fill_value=7)
print("\nFull_like result (filled with 7): ")
print(filled_array)


Full_like result (filled with 7): 
[[7 7 7]
 [7 7 7]]


Using the shape parameter: we can override the shape completely: 

In [32]:
filled_new_shape = np.full_like(template, fill_value=99, shape=(3,2))
print("Full_like result with shape = (3,2): ")
print(filled_new_shape)

Full_like result with shape = (3,2): 
[[99 99]
 [99 99]
 [99 99]]


In [2]:
import numpy as np
arr=np.array([[11,22,33],
              [44,55,66],
              [77,88,99]])
print(arr[1:,1:])
print(arr[:1,:1])

[[55 66]
 [88 99]]
[[11]]
