Copy in NumPy: The contents which are physically stored in another location, is known as copy. 

In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50])  #original array
copy_arr = arr.copy()   #copying the array
print("Original arr : ",arr)
arr[0] = 100 #changing the original array
print("After changes then original arr : ",arr)
print("Copied arr : ",copy_arr) 

#Therefore, changes made in original copy are not reflected in the original array




Original arr :  [10 20 30 40 50]
After changes then original arr :  [100  20  30  40  50]
Copied arr :  [10 20 30 40 50]


View in python : Returns view of the original array

In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50])  #original array
copy_arr = arr.view()
print("Original arr : ",arr)
arr[0] = 70   #changing the original array
print("After changes then original arr : ",arr)
print("Copied arr : ",copy_arr) 

#Hence changes in view also affects the original array

Original arr :  [10 20 30 40 50]
After changes then original arr :  [70 20 30 40 50]
Copied arr :  [70 20 30 40 50]


NumPy array Slicing Behaviour

note: Slicing creates views by default

In [ ]:
arr = np.array([1,2,3,4,5,6])
slice_view = arr[1:4]   #This creates a view by default
slice_copy = arr[1:4].copy()    #Explicit copy

print(f"Original : , {arr}")
print(f"Slice view : {slice_view}") 
print(f"Slice copy :  {slice_copy}")


#Modify slice view
slice_view[0] = 999
print(f"\nAfter modifying slice view: ")
print(f"Original :  {arr}")              #changed
print(f"Slice view : {slice_view}")      #changed
print(f"Slice copy : {slice_copy}")      #Unchanged

Original : , [1 2 3 4 5 6]
Slice view : [2 3 4]
Slice copy :  [2 3 4]

 After modifying slice view: 
Original :  [  1 999   3   4   5   6]
Slice view : [999   3   4]
Slice copy : [2 3 4]


NumPy array Indexing and Slicing

In [14]:
import numpy as np
#Accessing single elements
arr = np.array([10,20,30,40,50])
print("Array : ", arr)
print("aar[0]:", arr[0])        #First element -> 10
print("aar[2]:", arr[2])        #Third element -> 30
print("aar[4]:", arr[4])        #Last element -> 50

#Negative Indexing
print("\n")
print("arr[-1]:", arr[-1])      #Last element -> 50
print("arr[-3]:",arr[-3])       #Third from last -> 30
print("arr[-5]:",arr[-5])       #First element  -> 10

Array :  [10 20 30 40 50]
aar[0]: 10
aar[2]: 30
aar[4]: 50


arr[-1]: 50
arr[-3]: 30
arr[-5]: 10


Modifying Elements

In [15]:
import numpy as np
#Accessing single elements
arr = np.array([10,20,30,40,50])
arr[1] = 99     #change second element
arr[-2] = 77    #change second last element
print("Modified array : ", arr)  #[10,99,30,77,50]

Modified array :  [10 99 30 77 50]


1-D Array Slicing

Basic Slicing Syntax : [start:stop:step]

In [16]:
import numpy as np
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print("Original : ", arr)
print("arr[2:6] : ", arr[2:6])
print("arr[:4] : ", arr[:4])
print("arr[5:] : ", arr[5:])
print("arr[::2] : ", arr[::2])
print("arr[1::2] : ", arr[1::2])

Original :  [0 1 2 3 4 5 6 7 8 9]
arr[2:6] :  [2 3 4 5]
arr[:4] :  [0 1 2 3]
arr[5:] :  [5 6 7 8 9]
arr[::2] :  [0 2 4 6 8]
arr[1::2] :  [1 3 5 7 9]


Negative Indexing

In [18]:
import numpy as np
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print("Original : ", arr)
print("arr[-4:-1] : ", arr[-4:-1])
print("arr[-3:] : ", arr[-3:])
print("arr[:-3] : ", arr[:-3])
print("arr[::-1] : ", arr[::-1])


Original :  [0 1 2 3 4 5 6 7 8 9]
arr[-4:-1] :  [6 7 8]
arr[-3:] :  [7 8 9]
arr[:-3] :  [0 1 2 3 4 5 6]
arr[::-1] :  [9 8 7 6 5 4 3 2 1 0]


2D Array Indexing

In [ ]:
import numpy as np
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("2D Matrix : \n", matrix)
print("matrix[0,1]:", matrix[0,1])      #Row 0, col 1 -> 2
print("matrix[2,3]:", matrix[2,3])      #Row 2, col 3 -> 12
print("matrix[-1,-2]: ", matrix[-1,-2])     #Last row, col -2 -> 11

2D Matrix : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
matrix[0,1]: 2
matrix[2,3]: 12
matrix[-1,-2]:  11


2D Array Accessing Rows and columns

In [ ]:
import numpy as np
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("2D Matrix : \n", matrix) 
print("matrix[0,1]: ", matrix[0,1])     #Row 0 and col 1
print("matrix[2,3]:",matrix[2,3])   #Row 2 and col 3
print("matrix[-1,-2]: ", matrix[-1,-2]) #Last row, second last col -> 11

2D Matrix : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
matrix[0,1]:  2
matrix[2,3]: 12
matrix[-1,-2]:  11


In [33]:
import numpy as np 
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

#Accessing entire rows
print("Row 0 : ", matrix[0,:])  #First row
print("Row 1 : ", matrix[1])    #shorthand for row access
print("Row -1:", matrix[-1,:])   #Last row  

#Access entire columns
print("Column 0:", matrix[:,0])     #First column
print("Column 2: ", matrix[:,2])    #Third column
print("Column -1:", matrix[:,-1])   #last column 


Row 0 :  [1 2 3 4]
Row 1 :  [5 6 7 8]
Row -1: [ 9 10 11 12]
Column 0: [1 5 9]
Column 2:  [ 3  7 11]
Column -1: [ 4  8 12]


2D Array Slicing

In [34]:
import numpy as np
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("Rows 0-1, Cols 1-3:\n", matrix[0:2, 1:4])
print("Every other row, all cols:\n", matrix[::2,:])
print("All rows, every other col:\n", matrix[:,::2])
print("Bottom-right 2x2:\n", matrix[-2:,-2:])

Rows 0-1, Cols 1-3:
 [[2 3 4]
 [6 7 8]]
Every other row, all cols:
 [[ 1  2  3  4]
 [ 9 10 11 12]]
All rows, every other col:
 [[ 1  3]
 [ 5  7]
 [ 9 11]]
Bottom-right 2x2:
 [[ 7  8]
 [11 12]]


In [40]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

print(arr[0, 1])  # Access element in first row, second column (value is 2)
print(arr[1, 4])  # Access element in second row, fifth column (value is 10)


2
10


In [39]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

slice_rows = arr[0:2, 1:4]  # Slice rows 0 to 1 and columns 1 to 3
print(slice_rows)
# Output:
# [[ 2  3  4]
#  [ 7  8  9]]

all_columns_second_row = arr[1, :]  # All columns of second row
print(all_columns_second_row)  # Output: [6 7 8 9 10]

all_rows_third_column = arr[:, 2]  # All rows in third column
print(all_rows_third_column)  # Output: [3 8]


[[2 3 4]
 [7 8 9]]
[ 6  7  8  9 10]
[3 8]


In [38]:
import numpy as np

# Create a sample 2D array
arr = np.array([[10, 20, 30, 40], 
                [50, 60, 70, 80], 
                [90, 100, 110, 120]])

# Try these one by one and print results:

# 1. Access element at 2nd row, 3rd column
print(arr[1, 2])

# 2. Slice first two rows, first three columns
print(arr[0:2, 0:3])

# 3. Slice all rows, last two columns
print(arr[:, 2:4])

# 4. Extract third column for all rows
print("4 : ",arr[:, 2])

# 5. Access last row, last column
print(arr[-1, -1])

# 6. Slice last two rows and last two columns
print("6 : ",arr[-2:, -2:])

# 7. Access rows 0 and 2, columns 1 and 3
print("7",arr[[0, 2], :][:, [1, 3]])


70
[[10 20 30]
 [50 60 70]]
[[ 30  40]
 [ 70  80]
 [110 120]]
4 :  [ 30  70 110]
120
6 :  [[ 70  80]
 [110 120]]
7 [[ 20  40]
 [100 120]]


Boolean Indexing in Numpy?

In [43]:
import numpy as np

#create a 1D NumPy array
arr = np.array([10,20,30,40,50])

#Apply a condition: Select elements greater than 25
condition = arr > 15
print("Condition array : ", condition)
print("Elements greater than 25 : ", arr[condition])

Condition array :  [False  True  True  True  True]
Elements greater than 25 :  [20 30 40 50]


Direct Boolean Indexing

You don't even need to create a separate variable for the condition. You can directly use it inside the brackets:

In [45]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Elements <= 3:", arr[arr <= 3])  #[1,2,3]

#Multiple conditions 
print("Elements between 4 and 8 : ", arr[(arr > 4) & (arr < 8)])
print("Even elements : ", arr[arr % 2 == 0])    #[2 4 6 8 10]

#Boolean indexing with 2D arrays:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Elements > 5 in matrix:", matrix[matrix > 5])

Elements <= 3: [1 2 3]
Elements between 4 and 8 :  [5 6 7]
Even elements :  [ 2  4  6  8 10]
Elements > 5 in matrix: [6 7 8 9]


Boolean indexing with 2D arrays

In [46]:
import numpy as np

#create a 2D NumPy array
matrix = np.array([[5,10,15],
                  [20,25,30],
                  [35,40,45]])

#select elements greater than 20
result = matrix[matrix > 20]
print("Elements greater than 20 : ", result)



Elements greater than 20 :  [25 30 35 40 45]


Modify elements using Boolean Indexing

In [47]:
import numpy as np

#Create a 2D NumPy array
matrix = np.array([[5,10,15],
                   [20,25,30],
                   [35,40,45]])

#Replace all values greater than 25 with 0
matrix[matrix > 25] = 0
print(matrix)

[[ 5 10 15]
 [20 25  0]
 [ 0  0  0]]


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]], dtype = float, order = 'C', subok = False,copy=True)
print(arr)
result = arr * 2
print(result)

arr + 


[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
[[ 2.  4.  6.  8.]
 [10. 12. 14. 16.]]


In [57]:
import numpy as np

arr = np.array([1,2,3,4])
arr_1 = np.asarray(arr)
print(arr)
print(arr_1)

[1 2 3 4]
[1 2 3 4]


In [60]:
import numpy as np

arr = np.array([[[1,2],[3,4],[7,8]]])
print("Original shape:", arr.shape)    # (1, 3, 2)

# Option 1: Using flatten()
flat1 = arr.flatten()
print("Flattened with flatten():", flat1)  # Output: [1 2 3 4 7 8]

# Option 2: Using reshape(-1)
flat2 = arr.reshape(-1)
print("Flattened with reshape(-1):", flat2)  # Output: [1 2 3 4 7 8]

# Option 3: Using ravel()
flat3 = arr.ravel()
print("Flattened with ravel():", flat3)     # Output: [1 2 3 4 7 8]


Original shape: (1, 3, 2)
Flattened with flatten(): [1 2 3 4 7 8]
Flattened with reshape(-1): [1 2 3 4 7 8]
Flattened with ravel(): [1 2 3 4 7 8]
