What is Array Shape?

In [3]:
import numpy as np

#different shaped arrays
arr_1d = np.array([1,2,3,4,5])
arr_2d = np.array([[1,2,3],[4,5,6]])
arr_3d = np.array([[[1,2],[3,4],[5,6],[7,8]]])

print(f"1D shape: {arr_1d.shape}")
print(f"2D shape: {arr_2d.shape}")
print(f"3D shape: {arr_3d.shape}")

1D shape: (5,)
2D shape: (2, 3)
3D shape: (1, 4, 2)


Key Properties related to Shape:

In [6]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(f"Shape : {arr.shape}")
#(2,3) - 2 rows,3 columns

print(f"ndim : {arr.ndim}")
#2 - number of dimensions

print(f"size : {arr.size}")
#6 - total number of elements

print(f"dtype: {arr.dtype}")
#int64 - data type

print(f"itemsize: {arr.itemsize}")
#8 - bytes per element

Shape : (2, 3)
ndim : 2
size : 6
dtype: int64
itemsize: 8


In [2]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])

reduced = arr.reshape(-1)
print(reduced)

[1 2 3 4 5 6]


Example - reshape()

In [9]:
import numpy as np

#original 2D array (2rows, 3columns)
arr = np.array([[1,2,3],
                [4,5,6]])

#Reshape to 1D(flatten)
reduced = arr.reshape(6)  #or arr.reshape(-1) gives same output
print(reduced)



[1 2 3 4 5 6]


In [ ]:
import numpy as np

#Reshape from 1D to 2D
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

#convert 1d to 12 element 2d array
arr2 = arr.reshape(4,3)
print(arr2)
#so we have 4 rows with 3 elements each

#reshape from 1d to 3d
newarr = arr.reshape(2,3,2)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


reshape() return type?

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr.reshape(3,3).base)
#we got the original array as result and not None, so this is a view.

[1 2 3 4 5 6 7 8 9]


Flattening the Array's

In [ ]:
import numpy as np

#create 2d array
arr2 = np.array([[1,2,2,3],[4,5,7,8]])
print(arr2)
print(arr2.shape)   #(2,4)

#now reshape it
new_arr = arr2.reshape(-1) 
print(new_arr)  

#check the shape
print(new_arr.shape)    #(8,) -> It is 8 element in 1st dimension

[[1 2 2 3]
 [4 5 7 8]]
(2, 4)
[1 2 2 3 4 5 7 8]
(8,)


Shape manipulation transpose

In [ ]:
import numpy as np

#create a 2d array first
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

#now find it transpose
new_arr = np.transpose(arr2) 
#So we can see the original array and the transpose of the array
#row and column changed in 2d matrix
print(new_arr)


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


Assignment :1. Create a 1d array 2. then reshape it to a 2d array and 3. find the transpose of the 2d array

In [ ]:
import numpy as np

#create 1d array
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)

#now reshape 1d to 2d
arr2 = arr.reshape(4,2) #4row and 2col
print(arr2)

#find the transpose
arr_transpose = arr2.transpose()
print(arr_transpose)        #col to row and row to col

[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 3 5 7]
 [2 4 6 8]]


Shape Manipulation : flat and flatten methods

In [18]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

#now used flat method
flat_arr = arr.flat[5]
#function will return us value at index-5 in the flattening array
#so the flat function will return 1d iterator over the array
print(flat_arr)

[[1 2 3 4]
 [5 6 7 8]]
6


Using np.ravel()

In [20]:
import numpy as np

#2d array
arr = np.array([[1,2,3],[4,5,6]])

#using ravel()
raveled = np.ravel(arr)
print("Original array:")
print(arr)
print("\nRaveled(C-order, row-major)")
print(raveled)

raveled_f = np.ravel(arr, order ='F')
print("\nRaveled (F-order, column-major):")
print(raveled_f)

Original array:
[[1 2 3]
 [4 5 6]]

Raveled(C-order, row-major)
[1 2 3 4 5 6]

Raveled (F-order, column-major):
[1 4 2 5 3 6]


2. np.ravel() - 3D Array

In [22]:
arr_3d = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("\n3D array : ")
print(arr_3d)

raveled_3d = np.ravel(arr_3d)
print("\n3D array raveled:")
print(raveled_3d)


3D array : 
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

3D array raveled:
[1 2 3 4 5 6 7 8]


3. Using np.squeeze()

In [26]:
import numpy as np

arr_multi = np.array([[[1], [2], [3]]])  # Shape (1, 3, 1)
print("Original array shape:", arr_multi.shape)  

# To illustrate axis 2 has size 1
squeezed_axis = np.squeeze(arr_multi, axis=2)  
print("After squeeze(axis=2):")
print(squeezed_axis)  # Output: [[1 2 3]]
print("Shape:", squeezed_axis.shape)  # Shape: (1,3)


Original array shape: (1, 3, 1)
After squeeze(axis=2):
[[1 2 3]]
Shape: (1, 3)


3. Using np.squeeze

When you do np.squeeze(arr_multi, axis=1), it removes the axis 1 if its size is 1, so the shape changes from (3, 1) to (3,), not (3,1).

When you do np.squeeze(arr_multi) without axis, it removes all single-dimensional axes, also resulting in shape (3,).

So if your original array shape is (3,1), squeezing axis=1 results in a 1D array with shape (3,).

In [32]:
import numpy as np

arr_multi = np.array([[1], [2], [3]])  # shape (3,1)
print(arr_multi)
# Remove single dimension at axis=1
squeezed_axis = np.squeeze(arr_multi, axis=1)
print("After squeeze(axis=1):")
print(squeezed_axis)  # output: [1 2 3]
print("Shape:", squeezed_axis.shape)  # shape: (3,)

# Remove all single dimensions
squeezed_all = np.squeeze(arr_multi)
print("After squeeze() (all single dimensions):")
print(squeezed_all)  # output: [1 2 3]
print("Shape:", squeezed_all.shape)  # shape: (3,)


[[1]
 [2]
 [3]]
After squeeze(axis=1):
[1 2 3]
Shape: (3,)
After squeeze() (all single dimensions):
[1 2 3]
Shape: (3,)


In [1]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])

reduced = arr.reshape(7)
print(reduced)

ValueError: cannot reshape array of size 6 into shape (7,)