In [ ]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [3]:
import numpy as np

print(np.__version__)

2.3.4


In [4]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
import numpy as np
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


Create a 0-D array with value 42

In [6]:
import numpy as np

arr = np.array(42)

print(arr)

42


1D Arrays: : An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

In [7]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.

In [ ]:
# Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:
import numpy as np
arr = np.array([1,2,3])

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])

#create a Numpy a
print("Array : ", arr)

print("Type : ", type(arr))
print("Shape : ", arr.shape)
print("Data Type : ", arr.dtype)


Array :  [1 2 3 4 5]
Type :  <class 'numpy.ndarray'>
Shape :  (5,)
Data Type :  int64
