In [ ]:
import numpy as np

#Create a NumPy array
arr = np.array([1,2,3,4,5]) 

#Display the array
print("Array : ", arr)

#Show array attributes 
print("Type : ", type(arr)) 
print("Shape : ", arr.shape)
print("Data Type : ", arr.dtype) 


Array :  [1 2 3 4 5]
Type :  <class 'numpy.ndarray'>
Shape :  (5,)
Data Type :  int64


Compare Lists v/s NumPy Arrays:

In [ ]:
import numpy as np
import time

#python list
list_data = list(range(1000000))
start = time.time()
list_result = [x*2 for x in list_data]
print("Python list time : ", time.time() - start)

#NumPy array
array_data = np.arange(1000000)
start = time.time()
array_result = array_data * 2
print("NumPy array time: ", time.time() - start)


# NumPy was much faster for the same operation

Python list time :  0.06748700141906738
NumPy array time:  0.006058454513549805


ex- Using a python list

In [3]:
#using normal python lists :
numbers = [1,2,3,4,5]
result = [x * 2 for x in numbers]  #You must loop manaully
print(result)

[2, 4, 6, 8, 10]


NumPy performs operations on entire arrays at once, without explicit loops

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr * 2) #Multiply each element by 2 
print(arr + 10) #Add 10 to each element 
print(arr ** 2) #Square each element
print(np.sqrt(arr)) #Square root of each element 


[ 2  4  6  8 10]
[11 12 13 14 15]
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]


Array Broadcasting

Example 1: Adding a scalar to an array

In [ ]:
import numpy as np
arr = np.array([1,2,3])
result = arr + 5  #5 is broadcasted to match the array shape 
print(result)

#NUmpy automatically adds 5 to each element -- no loop required

[6 7 8]


Example 2 : Broadcasting between arrays

In [ ]:
import numpy as np 

arr1 = np.array([[1,2,3],[4,5,6]])

arr2 = np.array([10,20,30])

print(arr1 + arr2) 

[[11 22 33]
 [14 25 36]]


Example 1 : Memory Inspection

In [ ]:
import sys      #to check memory usage
import numpy as np

#Python list memory
py_list = [1,2,3,4,5]
print(f"List size : {sys.getsizeof(py_list)} bytes")        #gives the total memory (in bytes) used by the entire list.​
print(f"Per element :  {sys.getsizeof(py_list[0])} bytes")  #gives the memory used by just one element in the list.

#NumPy array memory
np_array = np.array([1,2,3,4,5])
print(f"NumPy size: {np_array.nbytes} bytes")  #gives the total memory (in bytes) used by all the numbers in the array.​
print(f"Per element :  {np_array.itemsize} bytes")  #gives the memory used by one element in the array.

List size : 104 bytes
Per element :  28 bytes
NumPy size: 40 bytes
Per element :  8 bytes


Example 2 : Operation Speed

In [12]:
import time 
import numpy as np

size = 1000000

#Python list
py_list = list(range(size))
start = time.time()     #records the start time.
result = [x * 2 for x in py_list]
py_time = time.time() - start

#NumPy array
np_array = np.arange(size)
start = time.time()
result = np_array * 2   #multiplies every number by 2 at once (vectorized operation).
np_time = time.time() - start

print(f"Python: {py_time:.4f}s")
print(f"NumPy: {np_time:.4f}s")
print(f"Speedup: {py_time/np_time:.1f}x")

Python: 0.1036s
NumPy: 0.0228s
Speedup: 4.6x
