Single Array Iteration

In [2]:
import numpy as np
#iterate 1d array
oned_arr = np.array([1,2,3,4,5,6,7])
for val in oned_arr:
    print(val)


1
2
3
4
5
6
7


Iterating a 2D Array(Nested Loop)

In [3]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print("Original array : \n", arr)
print("After iteration : ")
for x in arr:
    print(x)
    

Original array : 
 [[1 2 3]
 [4 5 6]]
After iteration : 
[1 2 3]
[4 5 6]


To iterate on each scalar:

In [4]:
print("After iterating on each scalar:")
for row in arr:
    for element in row:
        print(element)

        

After iterating on each scalar:
1
2
3
4
5
6


Iterating a 3D Array

In [5]:
import numpy as np
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for block in arr3:
    print("Block:\n", block)


Block:
 [[1 2]
 [3 4]]
Block:
 [[5 6]
 [7 8]]


In [6]:
for block in arr3:
    for row in block:
        for element in row:
            print(element)

1
2
3
4
5
6
7
8


Example - np.nditer()

In [10]:
#Let's iterate down to scalers in 3d array using nditer. 
#iterate 2d array
twod_arr = np.array([[1,2,3],[4,5,6]])
for val in np.nditer(twod_arr):
    print(val)
    

1
2
3
4
5
6


In [13]:
#now 3d array
thread_arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for val in np.nditer(thread_arr):
    print(val)

1
2
3
4
5
6
7
8
9


In [14]:
#now 4d array
four_darr = np.array([[[[1,2,3],[4,5,6],[7,8,9]]]])
for val in np.nditer(four_darr):
    print(val)

1
2
3
4
5
6
7
8
9


example-np.nditer()

In [ ]:
#iterate 2d array
twod_arr = np.array([[1,2,3],[4,5,6]])
for val in np.nditer(twod_arr[:,::2]):      #[[1,3],[4,6]]
    print(val)

1
3
4
6


Let's break down your code:

```python
twod_arr = np.array([[1,2,3],[4,5,6]])
for val in np.nditer(twod_arr[:,::2]):
    print(val)
```

### What each part does:
1. `twod_arr = np.array([[1,2,3],[4,5,6]])`
   - Creates a 2D numpy array:
     ```
     [[1, 2, 3],
      [4, 5, 6]]
     ```

2. `twod_arr[:,::2]`
   - This uses slicing on the 2D array:
     - `:` means "all rows"
     - `::2` means "every second column, starting from column 0"
   - For your array, this selects:
     - From each row, the columns at index 0 and 2.
     - So the result is:
       ```
       [[1, 3],
        [4, 6]]
       ```

3. `np.nditer(...)`
   - `np.nditer` is a NumPy tool for efficiently iterating (visiting) every element in an array, no matter the shape.
   - It flattens the array into a 1D sequence for the loop and yields each value one-by-one.

4. `for val in np.nditer(...): print(val)`
   - Iterates through all the elements in the selected subarray (`[[1,3],[4,6]]`) in row-major order:
     - First 1, then 3, then 4, then 6.
   - Each value is printed on its own line.

### Output:
```
1
3
4
6
```
- These are the elements at positions (0,0), (0,2), (1,0), and (1,2) in the original array.

***

**In summary:**  
- The code picks alternate columns from every row in your 2D array and prints each value using an efficient numpy iterator.



In [16]:
#iterate 2d array
fourd_arr = np.array([[[[1,2,3],[4,5,6]]]])
for val in np.nditer(fourd_arr[:,::3]):      #[[1,4]
    print(val)

1
2
3
4
5
6


Iterate over Transpose of array

In [ ]:
import numpy as np
a = np.array([[11,2,3,4],[29,4,15,6],[11,21,39,31]])
print("The array is : ")
print(a)

print("The transpose of the array is : ")
at = a.T
print(at) 
print("Iterating over the array: ")
for x in np.nditer(at):
    print(x, end = ' ')


The array is : 
[[11  2  3  4]
 [29  4 15  6]
 [11 21 39 31]]
The transpose of the array is : 
[[11 29 11]
 [ 2  4 21]
 [ 3 15 39]
 [ 4  6 31]]
Iterating over the array: 
11 2 3 4 29 4 15 6 11 21 39 31 

Controlling Iteration Order: 

In [22]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print("original array : \n", arr)
print("using nditer order = C:")
for x in np.nditer(arr, order="C"):
    print(x)
print()
print("using nditer order = F:")
for x in np.nditer(arr, order = "F"):
    print(x)

original array : 
 [[1 2 3]
 [4 5 6]]
using nditer order = C:
1
2
3
4
5
6

using nditer order = F:
1
4
2
5
3
6


Mention the order

In [24]:
import numpy as np
a = np.array([[1,2,3,4],[8,9,5,6],[10,20,29,31]])
print("\n The array:\n")
print(a)
print("\n The transpose of the array is : \n")
at = a.T
print(at) 
print("\nIterating over the transposed array\n")
for x in np.nditer(at):
    print(x,end = ' ')

print("\nIterating over transposed array in C-Style order:\n")
for x in np.nditer(at,order='C'):
    print(x, end =' ')


 The array:

[[ 1  2  3  4]
 [ 8  9  5  6]
 [10 20 29 31]]

 The transpose of the array is : 

[[ 1  8 10]
 [ 2  9 20]
 [ 3  5 29]
 [ 4  6 31]]

Iterating over the transposed array

1 2 3 4 8 9 5 6 10 20 29 31 
Iterating over transposed array in C-Style order:

1 8 10 2 9 20 3 5 29 4 6 31 

Numpy nd.ndenumerate()

In [25]:
import numpy as np
arr = np.array([10,20,30])
for index, value in np.ndenumerate(arr):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30


np.ndenumerate - 2D Array

In [26]:
import numpy as np
arr = np.array([[10,20,30],[40,50,60]])

for index,value in np.ndenumerate(arr):
    print(index, value)

(0, 0) 10
(0, 1) 20
(0, 2) 30
(1, 0) 40
(1, 1) 50
(1, 2) 60


np.ndenumerate - 3D Array

In [27]:
import numpy as np
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

for index, value in np.ndenumerate(arr):
    print(index, value)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8


Modify values using Indices:

In [28]:
import numpy as np
arr = np.array([[1,2],[3,4]])

for index,value in np.ndenumerate(arr):
    arr[index] = value * 10
print(arr)

[[10 20]
 [30 40]]


Numpy Broadcasting

Adding a vector to each row of a matrix without broadcasting:

In [ ]:
import numpy as np
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
vector = np.array([1,0,1])
result = np.empty_like(matrix)  # Creates an empty array with same shape and dtype as matrix

for i in range(matrix.shape[0]):
    result[i,:] = matrix[i,:] + vector
print(result)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


With Broadcasting:

In [31]:
result = matrix + vector
print(result)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


1D Array with 2D Array

In [ ]:
import numpy as np

#1D array broadcast to 2D array
vector = np.array([10,20])
matrix = np.array([[1,2],[3,4],[5,6]])

result = matrix + vector
print("Matrix + vector: ")
print(result)

Matrix + vector: 
[[11 22]
 [13 24]
 [15 26]]


Broadcasting with Dimension 1

In [35]:
import numpy as np

#column vector broadcasting 
column = np.array([[1],[2],[3]]) #shape: (3,1)
row = np.array([10,20,30])       #shape : (3,)

result = column + row
print("Column + Row : ")
print(result)

#column : (3,1) -> braodcast to (3,3)
#row : -> broadcast to (3,3)

Column + Row : 
[[11 21 31]
 [12 22 32]
 [13 23 33]]


Example pof Incompatible Shapes:

In [37]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]]) #shape (2,3)
b = np.array([1,2])  #shape : (2,)
print(a+b)


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 