In [1]:
a = [[[2,3,4,5],[77,66,44,3],[11,32,13,88]]]
b = a
print(b is a)

True


In [2]:
import numpy as np
a = np.array([1,2,3])
print(a.dtype)

int64


how to obtain element for 2nd row and 3rd column
options are: 
1. [1,2] 
2. [2][3]
3. [3,2]
4. [2,3] and ans is : 1. [1,2]

In [17]:
import numpy as np
b = np.array([1,2,3]) + np.array([4,5,6])
print(b)


[5 7 9]


In [20]:
import numpy as np
a = np.arange(10).reshape(2,5)
print(a)
print(a.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)


In [21]:
a = np.array([[1,2],[3,4],[5,6]])
b = a.flatten()
print(b)

[1 2 3 4 5 6]


In [33]:
import numpy as np
arr = np.array([10.8,20.89,30,12.34,20])
print(arr.itemsize)

8


In [29]:
import numpy as np
arr = np.array([10.8,20.89,30,12.34,20])
np.all(arr)

np.True_

make a 2*3 matrix of integers generating between 0 to 10 via np.random.rand?

In [32]:
import numpy as np

# Generate a 2x3 matrix of random integers between 0 and 9 (high is exclusive)
matrix = np.random.randint(low=0, high=10, size=(2, 3))

print(matrix)


[[3 7 1]
 [5 3 5]]


what does np.random.randn(3,2) does?The function `np.random.randn(3,2)` generates a 3x2 matrix of random numbers, where each value is sampled from the standard normal (Gaussian) distribution with mean 0 and standard deviation 1.[1][2][3][4]

- The returned array shape is (3, 2).
- All elements are floating-point numbers.
- Each value is independently drawn from the distribution \( N(0, 1) \).

So, this gives you 3 rows and 2 columns of random floats from the standard normal distribution.[2][5][9][1]


which numpy operation correct for square in array
1. arr * arr
2. arr ** 2
3. np.square(arr)
4. all of the above 
which option is correct?

The correct answer is:

**4. all of the above**

Explanation:
- `arr * arr` performs element-wise multiplication, effectively squaring each element.
- `arr ** 2` uses the power operator to square each element.
- `np.square(arr)` applies NumPy's square function element-wise to the array.

All three operations will produce the same result of squaring each element in the array.[1][3][5][7]



what does all() function do in numpy?

The np.all() function in NumPy tests whether all elements in an array evaluate to True. By default, it performs this check over the entire array, but you can specify an axis to check along a particular dimension. It returns a single Boolean value True if every element is True (or non-zero/non-false), otherwise False.​

Key points:
np.all(arr) returns True only if every element in arr is True.

You can specify axis to apply the check along rows, columns, or specific axes.

Useful for conditions checking, filtering, or validating array contents.

In [ ]:
import numpy as np

arr = np.array([[True, True], [True, False]])
print(np.all(arr))          # Outputs: False
print(np.all(arr, axis=0))  # Outputs: [ True False]
print(np.all(arr, axis=1))  # Outputs: [ True False]


True
[ True  True]
[ True  True]


In [34]:
import numpy as np

arr = np.array([[True, True], [True, False]])
print(np.all(arr))          # Outputs: False
print(np.all(arr, axis=0))  # Outputs: [ True False]
print(np.all(arr, axis=1))  # Outputs: [ True False]


False
[ True False]
[ True False]


Examples of np.all with axis parameter

Explanation:

axis=0 applies all() column-wise, reducing rows and returning a Boolean array for each column.

axis=1 applies all() row-wise, reducing columns and returning a Boolean array for each row.

Without axis, it checks all elements in the array at once

In [ ]:
import numpy as np

arr = np.array([[True, True, False],
                [True, True, True]])

# Check if all elements in the entire array are True
print(np.all(arr))  
# Output: False (because there is a False element)

# Check if all elements are True along axis 0 (columns)
print(np.all(arr, axis=0))  
# Output: [ True  True False] 
# Column-wise result: True only if all elements in that column are True

# Check if all elements are True along axis 1 (rows)
print(np.all(arr, axis=1))  
# Output: [False  True] 
# Row-wise: True only if all elements in that row are True
