Numpy Datatype

In [2]:
import numpy as np
arr1 = np.array([10,20,30])
print(arr1.dtype)
arr2 = np.array([10.5, 20.7, 30.1])
print(arr2.dtype)

int64
float64


In [3]:
arr3 = np.array([10,20,30], dtype='float32')
print(arr3)
print("Data Type :", arr3.dtype)

[10. 20. 30.]
Data Type : float32


Numpy Datatype Example

In [5]:
#Examples of creating Arrays with specific data types
import numpy as np

#Integers arrays
arr_int8 = np.array([10,20,30], dtype=np.int8)
print(f"int8 array : {arr_int8}, dtype: {arr_int8.dtype}")

#o/p : int8 array: [10 20 30], dtype: int8

#Float arrays
arr_float32 = np.array([1.5,2,7,3.9],dtype=np.float32)
print(f"float32 array: {arr_float32}, dtype: {arr_float32.dtype}")
#o/p : float32 array: [1.5 2.7 3.9], dtype: float32

#Boolean array
arr_bool = np.array([True, False, True], dtype = bool)
print(f"bool array : {arr_bool}, dtype: {arr_bool.dtype}")
#o/p : bool array : [True False True], dtype : bool

#complex array
arr_complex = np.array([1+2j, 3+4j], dtype=np.complex128)
print(f"complex array : {arr_complex}, dtype: {arr_complex.dtype}")
#o/p : complex array : [1.+2.j 3.+4.j], dtype: bool

int8 array : [10 20 30], dtype: int8
float32 array: [1.5 2.  7.  3.9], dtype: float32
bool array : [ True False  True], dtype: bool
complex array : [1.+2.j 3.+4.j], dtype: complex128


In [6]:
import numpy as np

#integer array with 1 byte per element
arr1 = np.array([10,20,30],dtype = 'i1')
print(arr1)
print("Datatype : ", arr1.dtype)

#Float array with 8 bytes per element
arr2 = np.array([1.5,2.5,3.5], dtype='f8')
print(arr2)
print("Datatype: ", arr2.dtype)

[10 20 30]
Datatype :  int8
[1.5 2.5 3.5]
Datatype:  float64


Memory Comparison

In [8]:
a = np.array([1,2,3], dtype='i1')   #int8(1byte)
b = np.array([1,2,3], dtype='i8')   #int64 (8bytes)

print("Memory used by a : ",a.nbytes, "bytes")
print("Memory used by b:", b.nbytes, "bytes")

Memory used by a :  3 bytes
Memory used by b: 24 bytes


Numpy Type Conversion

In [1]:
import numpy as np
original = np.array([1,2,3,4,5])
print(f"Original data type : {original.dtype}")

#converting to different types
to_float = original.astype(np.float64)
to_int16 = original.astype('int16')
to_string = original.astype('U10')  #Unicode string of length 10

print(f"To float : {to_float}, dtype: {to_float.dtype}")
print(f"To int16: {to_int16}, dtype: {to_int16.dtype}")
print(f"To U10: {to_string}, dtype: {to_string.dtype}")

#Type promotion during operations
int_array = np.array([1,2,3])
float_array = np.array([1.5, 2.5, 3.5])
result = int_array + float_array #int promoted to float
print(f"Result of operation : {result}, dtype: {result.dtype}")


Original data type : int64
To float : [1. 2. 3. 4. 5.], dtype: float64
To int16: [1 2 3 4 5], dtype: int16
To U10: ['1' '2' '3' '4' '5'], dtype: <U10
Result of operation : [2.5 4.5 6.5], dtype: float64


Waht if a value cannot be converted? If a value cannot be converted to target datatype THEN numpy will raise a value errror. 

In [11]:
arr = np.array(['10','20','thirty'])
print(arr)
#try converting to integer
new_arr = arr.astype(int)

['10' '20' 'thirty']


ValueError: invalid literal for int() with base 10: np.str_('thirty')