Comparison with Python tools(simple)

Multiply all elements by 2:

In [2]:
#A. Normal Loop
lst = [1,2,3,4,5]
out = []
for x in lst:
    out.append(x*2)
print(out)


[2, 4, 6, 8, 10]


In [4]:
#B. Using map()
out = list(map(lambda x: x*2,lst))
print(out)


[2, 4, 6, 8, 10]


In [6]:
#C. Using List Comprehension
out = [x*2 for x in lst]
print(out)

[2, 4, 6, 8, 10]


In [8]:
#D. Using NumPy Vectorization
import numpy as np
arr = np.array([1,2,3,4,5])
out = arr * 2
print(out)

[ 2  4  6  8 10]


1. np.vectorize() - Make any function vectorized

In [10]:
import numpy as np

#Regular python function
def classify_grade(score):
    if score >= 90:
        return 'A'
    elif score >= 80:
        return 'B'
    elif score >=70:
        return 'C'
    else:
        return 'F'
    
#vectorize it
vectorized_classify = np.vectorize(classify_grade)

#use on entire array 
scores = np.array([95,87,76,65,92])
grades = vectorized_classify(scores)
print(grades)


['A' 'B' 'C' 'F' 'A']


2. np.where()

In [ ]:
import numpy as np
ages = np.array([15,25,17,30,12,45])

#check if adult(18+)
status = np.where(ages >= 18,'Adult','Minor')
print(status)       #['Minor''Adult''Minor''Adult''Minor''Adult']

#Multiple conditions using logical operators
temperatures = np.array([25,35,15,40,20])
comfort = np.where(
    (temperatures >= 20) & (temperatures <= 30), 
    'Comfortable','Uncomfortable')
print(comfort)


['Minor' 'Adult' 'Minor' 'Adult' 'Minor' 'Adult']
['Comfortable' 'Uncomfortable' 'Uncomfortable' 'Uncomfortable'
 'Comfortable']


In [13]:
#Nested Conditions:
scores = np.array([95,85,75,65])
grades = np.where(scores >= 90, 'A',
                  np.where(scores >= 80,'B',
                           np.where(scores >= 70, 'C', 'F')))
print(grades)

['A' 'B' 'C' 'F']


3. np.select() - Multiple Condition

In [14]:
import numpy as np
scores = np.array([95,85,75,65,55])

#Define conditions and choices
conditions = [
    scores >= 90,
    (scores >= 80) & (scores < 90),
    (scores >= 70) & (scores < 80),
    (scores >= 60) & (scores < 70)
]

choices = ['A','B','C','D']
#Default value if no conditions is met
grades = np.select(conditions,choices,default='F')
print(grades)

['A' 'B' 'C' 'D' 'F']


Numpy Universal Functions (ufuncs)

In [15]:
import numpy as np
arr = np.array([1,2,3,4])
print(np.square(arr))

[ 1  4  9 16]


In [ ]:
import numpy as np
arr = np.array([1,4,9,16,25])

#Mathematical ufuncs
print(np.sqrt(arr))
print(np.square(arr))
print(np.exp(arr))      #Exponential
print(np.log(arr))      #Natural log


[1. 2. 3. 4. 5.]
[  1  16  81 256 625]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
[0.         1.38629436 2.19722458 2.77258872 3.21887582]


Binary ufuncs (take 2 inputs) - Aggregation Functions

In [ ]:
data = np.array([[1,2,3],[4,5,6],[7,8,9]])

#Aggregate entire array
print(np.sum(data))
print(np.mean(data))
print(np.std(data))
print(np.min(data))
print(np.max(data))

#Aggreagate along axis
print(np.sum(data, axis=0)) #column sum
print(np.sum(data,axis = 1)) #row sum


45
5.0
2.581988897471611
1
9
[12 15 18]
[ 6 15 24]
