Numpy Array Parameter :  numpy.array(object, dtype, copy,order, subok, dmin)

1. Object

In [ ]:
import numpy as np

#object can be a list
arr1 = np.array([1,2,3,4,5])

#object can be a tuple
arr2 = np.array((1,2,3))

#object can be nested lists for 2D arrays
arr3 = np.array([[1,2,3], [4,5,6]]) 


[[1 2 3]
 [4 5 6]]


2. dtype(optional)

In [ ]:
#Force integer type
arr_int = np.array([1.1, 2.2, 3.3], dtype = int)
print(arr_int)  #decimals are truncated 

[1 2 3]


In [6]:
#Force float type
arr_float = np.array([1,2,3], dtype=float)
print(arr_float)  

[1. 2. 3.]


In [7]:
#Complex numbers
arr_complex = np.array([1,2,3], dtype=complex)
print(arr_complex)

[1.+0.j 2.+0.j 3.+0.j]


3. copy(optional)  default : True, it make a new copy

In [11]:
original_list = [1,2,3]

#copy = True(default) creates independent copy

arr1 = np.array(original_list, copy = True)
arr1[0] = 999
print(original_list)    #o/p : [1,2,3] : unchanged


[1, 2, 3]


In [9]:
#copy = False - may use original data (if compatible)
arr2 = np.array(original_list, copy = False)
#Note : copy = False doesn't always work depends on data type

ValueError: Unable to avoid copy while creating an array as requested.
If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword.

4. order(optional)

by default - 'K' , Row major order : 'C', Column major order: 'F'

In [12]:
data = [[1,2,3], [4,5,6]]
#C- order(row-major) - default
arr_c = np.array(data, order = 'C')
print('C-order flattened:', arr_c.flatten())

C-order flattened: [1 2 3 4 5 6]


In [24]:
data = [[1,2,3], [4,5,6]]
arr_f = np.array(data, order='F')
print('F-order flattened:', arr_f.flatten(order='F'))

F-order flattened: [1 4 2 5 3 6]


5. subok

In [ ]:
class MyArray(np.ndarray):
    pass

original = np.array([1,2,3]).view(MyArray)

#subok =  False - returns basic numpy array
arr1 = np.array(original, subok=False)
print(type(arr1))  #<class 'numpy.ndarray'>

#subok = True -keeps the subclass
arr2 = np.array(original, subok = True)
print(type(arr2))    #<class '__main__.MyArray'>

# When subok=False, NumPy ignores the subclass and returns a plain numpy .ndarray.​
# When subok=True, NumPy keeps the subclass, so the result is still a MyArray.

# arr1 is a basic NumPy array.
# arr2 is still a MyArray (the subclass).


<class 'numpy.ndarray'>
<class '__main__.MyArray'>


6. ndmin(Optional)

In [ ]:
#1D input, but force 2D output
arr_2d = np.array([1,2,3], ndmin=2)
print(arr_2d)
print(arr_2d.shape) #(1,3) as it has 1 row and 3 col

#Force 3D output
arr_3d = np.array([1,2,3], ndmin=3)
print(arr_3d)
print(arr_3d.shape)

# The shape parameter in NumPy tells you how many elements are in each dimension of an array. It is shown as a tuple, where each number represents the size of that dimension.

[[1 2 3]]
(1, 3)
[[[1 2 3]]]
(1, 1, 3)


Numpy Array Property

1. ndarray.ndim - Number of dimensions

In [28]:
import numpy as np
#0-dimensional array(scalar)
arr_0d = np.array(5)
print("0D array ndim: ", arr_0d.ndim)

#1-dimensional array(vector)
arr_1d = np.array([1,2,3,4])
print("1D array ndim: ",arr_1d.ndim)

#2-dimensional array(matrix)
arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array ndim: ",arr_2d.ndim)

#3-dimensional array(matrix)
arr_2d = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print("3D array ndim :", arr_3d.ndim)

0D array ndim:  0
1D array ndim:  1
2D array ndim:  2
3D array ndim : 3


2. ndarray.shape - Dimensions of the array: Returns a tuple showing the size of the array in each dimension.

In [2]:
import numpy as np

#1D array - shape is (number_of_elements,)
arr_1d = np.array([1,2,3,4,5])
print("1D shape : ", arr_1d.shape)

1D shape :  (5,)


In [4]:
import numpy as np

#2D array - shape is (rows, columns)
arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D shape : ", arr_2d.shape)

2D shape :  (2, 3)


In [5]:
import numpy as np

#3D array - shape is (depth, rows, columns)
arr_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("3D shape : ", arr_3d.shape)

3D shape :  (2, 2, 2)


3. ndarray.size - Total number of Elements.\n
It returns the total number of elements in the entire array.

In [6]:
import numpy as np
arr_1d = np.array([1,2,3,4,5])
print("1D size: ", arr_1d.size)

1D size:  5


In [ ]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D size : ", arr_2d.size)  #output = 6(2rows x 3cols)

2D size :  6


In [ ]:
arr_3d = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print("3D size : ", arr_3d.size) #outpt = 8(2x2x2 = 8 elements)

3D size :  8


4. ndarray.dtype - Data Type of elements: Shows the data type of the elements in the array

In [9]:
import numpy as np
#integers arrays
int_arr = np.array([1,2,3])
print("Integer dtype : ", int_arr.dtype)

Integer dtype :  int64


In [ ]:
#Float arrays
float_arr = np.array([1.1,2.2,3.3])
print("Float dtype : ", float_arr.dtype)  

Float dtype :  float64


In [11]:
#Explicit dtype specification
custom_arr = np.array([1,2,3], dtype=np.float32)
print("Custom dtype : ", custom_arr.dtype)

Custom dtype :  float32


In [13]:
#Boolean array
bool_arr = np.array([True, False, True])
print("Boolean dtype : ", bool_arr.dtype)

Boolean dtype :  bool


5. ndarray.itemsize - Size of each elements in Bytes: It returns the memory size (in bytes) of each array element.

In [14]:
import numpy as np

#int32 typically uses 4 bytes
int32_arr = np.array([1,2,3],dtype = np.int32)
print("int32 itemsize: ", int32_arr.itemsize,"bytes")

int32 itemsize:  4 bytes


In [15]:
#float32 typically uses 4 bytes 
float32_arr = np.array([1.1, 2.2, 3.3], dtype = np.float32)
print("float32 itemsize: ", float32_arr.itemsize,"bytes")

float32 itemsize:  4 bytes


In [17]:
#calculate total memory usage
arr = np.array([1,2,3,4,5], dtype=np.int64)
total_memory = arr.size * arr.itemsize
print(f"Total memory : {total_memory} bytes(5 elements x 8 bytes each)")

Total memory : 40 bytes(5 elements x 8 bytes each)


Numpy array property - Putting it All Together

In [29]:
import numpy as np

#create a sample 2D array
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("Array:")
print(matrix)
print("\nProperties")
print("Dimensions (ndim):", matrix.ndim)
print("Shape (rows,columns):",matrix.shape)
print("Total elements (size):", matrix.size)
print("Data type (dtype):",matrix.dtype)
print("Bytes per element (itemsize):",matrix.itemsize)
print("Total memory (size x itemsize):", matrix.size * matrix.itemsize, "bytes")

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Properties
Dimensions (ndim): 2
Shape (rows,columns): (3, 4)
Total elements (size): 12
Data type (dtype): int64
Bytes per element (itemsize): 8
Total memory (size x itemsize): 96 bytes
