
1. From Python list or tuple (np.array):

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr)  # Output: [1 2 3 4]

[1 2 3 4]


1.5. Using np.asarray:
Similar to np.array but doesn’t copy if the input is already an ndarray.

In [ ]:
lst = [1, 2, 3]
arr = np.asarray(lst)
print(arr) 

[1 2 3]


2. All zeros (np.zeros): Creates an array filled with zeros of a specified shape.

In [2]:
zeros_arr = np.zeros((2, 3))
print(zeros_arr)
# Output: 
# [[0. 0. 0.]
#  [0. 0. 0.]]


[[0. 0. 0.]
 [0. 0. 0.]]


3. All ones (np.ones): Creates an array filled with ones of a specified shape.

In [3]:
ones_arr = np.ones((3, 2))
print(ones_arr)
# Output:
# [[1. 1.]
#  [1. 1.]
#  [1. 1.]]


[[1. 1.]
 [1. 1.]
 [1. 1.]]


4. Empty array (np.empty): Creates an uninitialized array (values will be random/garbage).

In [4]:
empty_arr = np.empty((2, 2))
print(empty_arr)
# Output: (random values)


[[0.00000000e+000 1.21010509e-311]
 [1.21010509e-311 1.21010509e-311]]


5. Full array (np.full): Creates an array filled with a specified value.

In [ ]:
full_arr = np.full((2, 2), 7)
print(full_arr)
# Output:
# [[7 7]
#  [7 7]]

6. Range of values (np.arange): Creates an array with regularly spaced values between start and stop.

In [ ]:
range_arr = np.arange(1, 10, 2)
print(range_arr)  # Output: [1 3 5 7 9]

7. Linearly spaced values (np.linspace):Creates an array with a specified number of evenly spaced values between start and stop.

In [ ]:
linspace_arr = np.linspace(0, 1, 5)
print(linspace_arr)  # Output: [0.   0.25 0.5  0.75 1.  ]

8. Identity matrix (np.eye): Creates a 2D identity matrix with ones on the diagonal.

In [5]:
identity = np.eye(3)
print(identity)
# Output:
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


9. Random arrays (np.random.rand): Creates arrays with random values between 0 and 1.

In [6]:
random_arr = np.random.rand(2, 3)
print(random_arr)

[[0.65000896 0.39943672 0.15143955]
 [0.93588331 0.81346213 0.11561482]]
